# -*- coding: utf-8 -*-
"""Covid-19 Clinical Trails Dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EctCI-eVXBhnye_9q5nDxAjNLjBXezSa
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sn

from google.colab import files
files.upload()

df = pd.read_csv('COVID clinical trials.csv')
df

df.head()

df.head(-5)

df.tail()

df.tail(-5)

df.shape

df.size

df.columns

df.dtypes

df.describe(include='int')

df.describe(include='all')

df.info()

df = df.drop_duplicates()

df.drop(columns='Study Documents', inplace=True)

df.columns

df['Phases'].fillna('None', inplace=True)
df['Phases']

df['Results First Posted'].isnull().sum()

df['Results First Posted'].fillna('None', inplace=True)
df['Results First Posted'].isnull().sum()

df['Results First Posted'].dtypes

df['Acronym'].fillna('None', inplace=True)
df['Acronym'].isnull().sum()

df.isnull().sum()

df.dropna(inplace=True)
df

df.isnull().sum()

df.shape

# Sample grouped data (replace this with your own DataFrame groupby result)
gender_counts = df.groupby('Gender')['Rank'].count()

# Create bar chart
plt.figure()
bars = plt.bar(gender_counts.index, gender_counts.values, color='skyblue')

# Add labels on top of each bar
for bar in bars:
    height = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2, height,
             str(height), ha='center', va='bottom', fontsize=10)

# Axis labels and title
plt.title("Gender-wise Rank Count")
plt.xlabel("Gender")         # ⬅ X-axis label
plt.ylabel("Count of Rank")  # ⬅ Y-axis label
plt.grid(True)
plt.show()

df['Gender'].value_counts().plot(kind='bar')

df['Status'].value_counts().plot(kind='pie', autopct='%1.1f%%')

plt.figure(figsize=(8, 5))
plt.hist(df['Enrollment'].dropna(), bins=30, color='lightgreen', edgecolor='black')
plt.title('Enrollment Distribution in Clinical Trials')
plt.xlabel('Enrollment Count')
plt.ylabel('Number of Trials')
plt.grid(axis='y')
plt.tight_layout()
plt.show()

df['Study Type'].value_counts().plot(kind='bar')

pd.crosstab(df['Phases'], df['Gender']).plot(kind='bar', stacked=True)

df['Start Year'] = pd.to_datetime(df['Start Date'], errors='coerce').dt.year
df['Start Year'].value_counts().sort_index().plot()

import seaborn as sns
sns.countplot(x='Study Results', data=df)

df['Sponsor/Collaborators'].value_counts().head(10).plot(kind='bar')

# Check unique values
print(df['Status'].value_counts())
print(df['Gender'].unique())